### ISSUE TITLE
callback from calendar granting failed

### ISSUE THREAD

**Issue by cmoifranck** [jderuette/zc_meeting#3]
From a normal http installation, the callback performed after granting OCM to manage my calendar pointed to the 8080 instead of the 8082 used by the application.
It results by a 403 error.
Manually correct the 8080 by 8082 bypass the issue and grants are OK.

**Comment by jderuette** [comment]
# Short : 
Check your environment var ZEROCLICK_URL

# Detailled : 
CallBack URI is built using two properties (in [GoogleApiHelper#getRedirectUri()](https://github.com/jderuette/zc_meeting/blob/staging/meeting.client/src/main/java/org/zeroclick/meeting/client/google/api/GoogleApiHelper.java#L129)) : 
1. ApplicationUrlProperty (`zeroclick.url`): this the front URL, manage by environment var (`ZEROCLICK_URL`). the default port is `http://localhost:8082`. Your environment variable should  change it (probably in your user .profile file).
2. GoogleCallbackUrlProperty (`contacts.api.google.callback.url`) should not be changed, because this URL is mapped in [web.xml file](https://github.com/jderuette/zc_meeting/blob/staging/meeting.ui.html.app.dev/src/main/webapp/WEB-INF/web.xml#L55).

**Comment by cmoifranck** [comment]
zeroclick.url is OK and standard.
ZEROCLICK_SERVER_URL="localhost:8080"
ZEROCLICK_SERVER_URL_PROTOCOL="http"
ZEROCLICK_URL="localhost:8082"
ZEROCLICK_URL_PROTOCOL="http"

In the web.xml file :
contacts.api.google.callback.url=/oauth2callback


So, i'm still having the same behavior : can't add a new calendar at startup...
